In [23]:
import numpy as np

G = 70e9
r = 30e-3
t = 2e-3
Ip = 2*np.pi*r**3*t
L = 2
T0 = 300


Le = L/2
Ke = G*Ip/Le * np.array([[1, -1],[-1, 1]])
f = np.array([[T0],[0]])
K = np.zeros((2, 2))
K[:,:] = Ke[:,:]
K[-1, -1] += Ke[-1, -1]

a = np.linalg.solve(K, f)
display(Ke, K, f, a)

array([[ 23750.44046114, -23750.44046114],
       [-23750.44046114,  23750.44046114]])

array([[ 23750.44046114, -23750.44046114],
       [-23750.44046114,  47500.88092228]])

array([[300],
       [  0]])

array([[0.02526269],
       [0.01263134]])

In [35]:
# d)
s = 3e4
f = np.array([[T0],[0], [0]])
K = np.zeros((3, 3))
K[0, 0] = K[-1, -1] = Ke[0, 0]
K[1, 1] = 2*Ke[1, 1]
K[0, 1] = K[1, 0] = K[1, 2] = K[2, 1] = Ke[0, 1]
K[-1, -1] += s
a = np.linalg.solve(K, f)
display(K, f, a)

array([[ 23750.44046114, -23750.44046114,      0.        ],
       [-23750.44046114,  47500.88092228, -23750.44046114],
       [     0.        , -23750.44046114,  53750.44046114]])

array([[300],
       [  0],
       [  0]])

array([[0.03526269],
       [0.02263134],
       [0.01      ]])